security:
    enable_authenticator_manager: true

    providers:
      app_user_provider:
          entity:
              class: App\Entity\Personel
              property: username

    password_hashers:
        App\Entity\Personel:
            algorithm: bcrypt

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~
            provider: app_user_provider

    access_control:
    
        - { path: ^/api/update, roles: PUBLIC_ACCESS}
        - { path: ^/api/admin, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }





